package com.nhnent.guestbook.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.springframework.stereotype.Repository;

import com.mysql.jdbc.Statement;
import com.nhnent.guestbook.model.GuestBook;

@Repository
public class GuestBookDao {
	private SqlSession sqlSession;

	public void setSqlSession(SqlSession sqlSession) {
		this.sqlSession = sqlSession;
	}

	public int insert(GuestBook guestBook) {
		Connection con;
		try {
			Class.forName("com.mysql.jdbc.Driver");
			con = DriverManager
					.getConnection(
							"jdbc:mysql://127.0.0.1:3306/guestbook?useUnicode=true&characterEncoding=euckr",
							"root", "0415");
			java.sql.Statement st = null;
			st = con.createStatement();
			String query = " insert into guestbook (email, password, content, create_date)"
					+ " values (?, ?, ?, ?)";
			Calendar cal = Calendar.getInstance();
			Date date = new Date(cal.getTimeInMillis());
			PreparedStatement preparedStmt = con.prepareStatement(query,
					Statement.RETURN_GENERATED_KEYS);
			preparedStmt.setString(1, guestBook.getEmail());
			preparedStmt.setString(2, guestBook.getPassword());
			preparedStmt.setString(3, guestBook.getContent());
			preparedStmt.setDate(4, date);
			preparedStmt.execute();
			ResultSet tableKeys = preparedStmt.getGeneratedKeys();
			tableKeys.next();
			int autoGeneratedID = tableKeys.getInt(1);
			preparedStmt.close();
			con.close();
			return autoGeneratedID;
		} catch (Exception e) {
			e.printStackTrace();
		}
		return 0;
	}

	public int getListSize() {
		Connection con;

		try {
			Class.forName("com.mysql.jdbc.Driver");

			con = DriverManager
					.getConnection(
							"jdbc:mysql://127.0.0.1:3306/guestbook?useUnicode=true&characterEncoding=euckr",
							"root", "0415");

			String query = "SELECT * FROM guestbook";

			// create the java statement
			java.sql.Statement st = con.createStatement();

			// execute the query, and get a java resultset
			ResultSet rs = st.executeQuery(query);
			int rowCount = 0;
			if (rs.last()) {
				rowCount = rs.getRow();
				rs.beforeFirst();
			}
			System.out.println(rowCount);
			while (rs.next()) {
				System.out.println("ddd");
			}
			return rowCount;
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return 0;

	}
	public GuestBook getGuestBook(int id) {
		Connection con;
		List<GuestBook> guestBookList = new ArrayList<GuestBook>();
		try {
			Class.forName("com.mysql.jdbc.Driver");

			con = DriverManager
					.getConnection(
							"jdbc:mysql://127.0.0.1:3306/guestbook?useUnicode=true&characterEncoding=euckr",
							"root", "0415");

			String query = "SELECT * FROM guestbook WHERE id = "+ id;
			java.sql.Statement st = con.createStatement();
			ResultSet rs = st.executeQuery(query);
			if(rs.next()){
				GuestBook guestBook = new GuestBook(rs.getInt("id"),
						rs.getString("email"), rs.getString("password"),
						rs.getString("content"), rs.getDate("create_date"));
				System.out.println(guestBook.getContent());
				guestBookList.add(guestBook);
				return guestBook;
			}
			
			System.out.println(guestBookList.size());
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
		
	}
	public List<GuestBook> getGuestBookList() {
		Connection con;
		List<GuestBook> guestBookList = new ArrayList<GuestBook>();
		try {
			Class.forName("com.mysql.jdbc.Driver");

			con = DriverManager
					.getConnection(
							"jdbc:mysql://127.0.0.1:3306/guestbook?useUnicode=true&characterEncoding=euckr",
							"root", "0415");

			String query = "SELECT * FROM guestbook";
			java.sql.Statement st = con.createStatement();
			ResultSet rs = st.executeQuery(query);
			while (rs.next()) {
				GuestBook guestBook = new GuestBook(rs.getInt("id"),
						rs.getString("email"), rs.getString("password"),
						rs.getString("content"), rs.getDate("create_date"));
				guestBookList.add(guestBook);
			}
			System.out.println(guestBookList.size());
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}

		return guestBookList;
	}

	public String getPassword(int id) {
		Connection con;
		try {
			Class.forName("com.mysql.jdbc.Driver");

			con = DriverManager
					.getConnection(
							"jdbc:mysql://127.0.0.1:3306/guestbook?useUnicode=true&characterEncoding=euckr",
							"root", "0415");

			String query = "SELECT * FROM guestbook WHERE id = " + id;
			java.sql.Statement st = con.createStatement();
			ResultSet rs = st.executeQuery(query);
			if (rs.next()) {
				return rs.getString("password");
			}
			else{
				return null;
			}
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}

	public void changeGuestBook(GuestBook guestBook) {
		Connection con;
		try {
			Class.forName("com.mysql.jdbc.Driver");

			con = DriverManager
					.getConnection(
							"jdbc:mysql://127.0.0.1:3306/guestbook?useUnicode=true&characterEncoding=euckr",
							"root", "0415");

			java.sql.Statement stmt = con.createStatement();

			String dbCommand = "update guestbook set content = '"
					+ guestBook.getContent() + "' where id = " + guestBook.getId();

			// 4) 쿼리문 실행 (반환값 integer type)
			stmt.executeUpdate(dbCommand);
			Calendar cal = Calendar.getInstance();
			Date date = new Date(cal.getTimeInMillis());
			dbCommand = "update guestbook set change_date  = '"
					+ date + "' where id = " + guestBook.getId();

			// 4) 쿼리문 실행 (반환값 integer type)
			stmt.executeUpdate(dbCommand);
			con.close();
			stmt.close();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	
	}

	

}
