package com.nhnent.guestbook.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.mysql.jdbc.Statement;
import com.nhnent.guestbook.model.GuestBook;
import com.nhnent.guestbook.service.MySqlConnection;

@Repository
public class GuestBookDao {
	@Autowired
	private MySqlConnection mySqlConnection;
	private SqlSession sqlSession;

	public void setSqlSession(SqlSession sqlSession) {
		this.sqlSession = sqlSession;
	}

	public int insert(GuestBook guestBook) {
		Connection con = mySqlConnection.getConnection();

		java.sql.Statement st = null;
		try {
			st = con.createStatement();
			String query = " insert into guestbook (email, password, content, create_date)"
					+ " values (?, ?, ?, ?)";
			Calendar cal = Calendar.getInstance();
			Date date = new Date(cal.getTimeInMillis());
			PreparedStatement preparedStmt = con.prepareStatement(query,
					Statement.RETURN_GENERATED_KEYS);
			preparedStmt.setString(1, guestBook.getEmail());
			preparedStmt.setString(2, guestBook.getPassword());
			preparedStmt.setString(3, guestBook.getContent());
			preparedStmt.setDate(4, date);
			preparedStmt.execute();
			ResultSet tableKeys = preparedStmt.getGeneratedKeys();
			tableKeys.next();
			int autoGeneratedID = tableKeys.getInt(1);
			preparedStmt.close();
			con.close();
			return autoGeneratedID;
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return -1;

	}

	public GuestBook getGuestBook(int id) {
		Connection con = mySqlConnection.getConnection();
		List<GuestBook> guestBookList = new ArrayList<GuestBook>();
		try {
			
			String query = "SELECT * FROM guestbook WHERE id = " + id;
			java.sql.Statement st = con.createStatement();
			ResultSet rs = st.executeQuery(query);
			if (rs.next()) {
				GuestBook guestBook = new GuestBook(rs.getInt("id"),
						rs.getString("email"), rs.getString("password"),
						rs.getString("content"), rs.getDate("create_date"));
				guestBookList.add(guestBook);
				return guestBook;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;

	}

	public List<GuestBook> getGuestBookList() {
		Connection con = mySqlConnection.getConnection();
		List<GuestBook> guestBookList = new ArrayList<GuestBook>();
		try {

			String query = "SELECT * FROM guestbook";
			java.sql.Statement st = con.createStatement();
			ResultSet rs = st.executeQuery(query);
			while (rs.next()) {
				GuestBook guestBook = new GuestBook(rs.getInt("id"),
						rs.getString("email"), rs.getString("password"),
						rs.getString("content"), rs.getDate("create_date"));
				guestBookList.add(guestBook);
			}
		}  catch (SQLException e) {
			e.printStackTrace();
		}

		return guestBookList;
	}

	public String getPassword(int id) {
		Connection con = mySqlConnection.getConnection();
		try {
			
			String query = "SELECT * FROM guestbook WHERE id = " + id;
			java.sql.Statement st = con.createStatement();
			ResultSet rs = st.executeQuery(query);
			if (rs.next()) {
				return rs.getString("password");
			} else {
				return null;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}

	public void changeGuestBook(GuestBook guestBook) {
		Connection con = mySqlConnection.getConnection();
		try {


			java.sql.Statement stmt = con.createStatement();

			String dbCommand = "update guestbook set content = '"
					+ guestBook.getContent() + "' where id = "
					+ guestBook.getId();

			// 4) 쿼리문 실행 (반환값 integer type)
			stmt.executeUpdate(dbCommand);
			Calendar cal = Calendar.getInstance();
			Date date = new Date(cal.getTimeInMillis());
			dbCommand = "update guestbook set change_date  = '" + date
					+ "' where id = " + guestBook.getId();

			// 4) 쿼리문 실행 (반환값 integer type)
			stmt.executeUpdate(dbCommand);
			con.close();
			stmt.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
